### ISSUE TITLE
No downloadables on pypi

### ISSUE THREAD

**Issue by nnathan** [CowboyTim/python-storable#1]
Hi Tim,

Do you mind setting up a release on pypi, there appears to be a directory on pypi but empty: https://pypi.python.org/simple/storable/.

Thanks.

**Comment by exhuma** [comment]
Hi @nnathan,

I'm currently working on a new release. It's getting close to being finished. There's still the odd thing to document, and merged into upstream. Once that's done, it will get released.

**Comment by exhuma** [comment]
Aaaaaand the deed is done! Version 1.0 has been released a minute ago!

Given that there's quite a bunch of changes due to Python 3 support you may want to double-check if I did not squeeze in some stupidities...
