### ISSUE TITLE
Clarify questions for the contribution guide

### ISSUE THREAD

**Issue by exhuma** [CowboyTim/python-storable#3]
I'd like to clarify a couple of questions for the contrinution guide:

* Version Scheme: Okay with [semantic versioning](http://www.semver.org)?
* git workflow: Okay with [this workflow](http://nvie.com/posts/a-successful-git-branching-model/)?

I'll add these notes to the contribution guide already. If there are other ideas I'm all ears ;)

**Comment by exhuma** [comment]
Planning to release the upcoming version as "1.0" (if we decide to stick with semver).

**Comment by CowboyTim** [comment]
The versioning scheme is nice. In fact, that's what everyone uses for ages, so I think we should do the same.

For the git use, it's nice and documented. 

At my day job, I voted against the extra "develop" branch though as there's no added functionality that master is kept clean as now "develop" is the one that gets dirty. "master" can be dirty IMO as the tags are ment  to be clean - you can even branch for hotfixes from them. But I'm not for using a dirty master way of working here, as it's easier to just use an off-the-shelves established principal that most people are using already :-).

**Comment by exhuma** [comment]
100% agree. I'll add this to the contribution guide. I think I'll get around doing this later today on my commute home. Once it's in, I'll close the issue and we can finalise the release.

**Comment by exhuma** [comment]
Done in 2600de6d457f8
