### ISSUE TITLE
PerlStorableException Структура не разобрана до конца

### ISSUE THREAD

**Issue by jolsen71** [CowboyTim/python-storable#7]
When attempting to thaw a particular simple frozen data structure, I get a `PerlStorableException Структура не разобрана до конца`. 

Using python_perl_storable 0.0.9 and python 3.9.0. I've attached the frozen structure as saved from our database. 

[exception.zip](https://github.com/CowboyTim/python-storable/files/5705992/exception.zip)

Please advise. Thanks!

**Comment by CowboyTim** [comment]
I'm sorry, that's an issue to be reported for the https://github.com/darviarush/python-perl-storable project

**Comment by jolsen71** [comment]
/facepalm. Sorry about overlooking that they were two different packages. I switched to yours and everything seems to be working. Thanks!
