### ISSUE TITLE
Package not compatible with zipapp: solution provided

### ISSUE THREAD

**Issue by manueldeprada** [CowboyTim/python-storable#8]
I use to package my apps using zippapp, for example: 
`python -m zipapp -c myapp -p "/usr/bin/env python3"`

This way, all my packages and its dependencies are compressed and packaged into a .pyz file that can be easily deployed and executed.

The problem with your package is that with zipped python files, you cannot use file.read inside the zip package, it can just contain .py files.

Your package is incompatible just because of this:
https://github.com/CowboyTim/python-storable/blob/715a66467ee734ba89de140be7f5c3800d216185/storable/__init__.py#L29
So I suggest you to hard code the version number inside __init__.py, if the build process does not depend on that.
This would also have the advantage to be more efficient, as your package will not need to read from disk each time its instantiated.

**Comment by CowboyTim** [comment]
Indeed, I think it's better without the open at import. I've removed the version.txt and hardcoded the 1.2.3 version instead. I did this on master directly, so best is to wait for the pipeline to start using this.

**Comment by CowboyTim** [comment]
Version 1.2.4 is published to pypi.org.
