### ISSUE TITLE
Version and byte order mismatch with Perl storable

### ISSUE THREAD

**Issue by frank-lenormand** [CowboyTim/python-storable#9]
Hi,

I’m trying to use `python-storage` to generate a file that could be picked up by regular Perl Storable.

The issue is that the data written by the former are not accepted by a program that uses the latter.

When I run `file`, I get two different file-format versions and byte orders, I wonder if that’s not the source of the problem:

```
# python-storable
perl Storable (v0.7) data (network-ordered) (major 2) (minor 9)

# file generated and read by program using Perl Storable
perl Storable (v0.7) data (major 2) (minor 11)
```

I don’t know Perl and haven’t tried making a script that could validate a file passed as input, could the above differences be relevant?

Thanks!

**Comment by frank-lenormand** [comment]
I have more information.

I have generated a dummy file containing only (supposedly) a list:

```
>>> import storable.output
>>> fout=open("out.dat", "wb")
>>> fout.write(storable.output.serialize([]))
```

```
$ file out.dat 
out.dat: perl Storable (v0.7) data (network-ordered) (major 2) (minor 9)
```

Then, I wrote a (minimal) Perl script to see if there were any errors loading the files:

```
#!/usr/bin/perl

require Storable;

# “clean” file, loads fine
print Storable::retrieve("watched_videos.dat"), "\n"; # returns `ARRAY(0x55dd8c992f78)`

# generated by `python-storable`
print Storable::retrieve("out.dat"), "\n";# returns `REF(0x55dd8c9ddcf0)`
```

The file generated with `storable.output.serialize()` doesn’t get `retrieve`d by `Perl::Storable` as an array, but a “ref”, which I believe is the root cause of my issue.

Note that `python-storable` has no issues loading either files:

```
>>> import storable
>>> storable.retrieve("out.dat")
[]
>>> storable.retrieve("watched_videos.dat")
[array of data, removed]
```

I’m not sure which version of `Perl::Storable` I’m using, may be `3.15`.

**Comment by CowboyTim** [comment]
I think I fixed this now. Note that the API is changed a bit to be more consistent with perl Storable's API. So:

```
>>> import storable
>>> fout=open("out.dat", "wb")
>>> fout.write(storable.freeze([]))
```
I haven't implemented Storable's nfreeze (yet), which uses network-order byte ordening and is more architecture independent.
